const texts = [
    "The quick brown fox jumps over the lazy dog.",
    "Learning to code is both fun and challenging.",
    "Artificial Intelligence is transforming the world.",
    "Practice makes perfect, so keep trying.",
    "Technology is evolving faster than ever before.",
    "Reading books can expand your knowledge and perspective.",
    "A healthy diet is essential for a long and happy life.",
    "The Internet has revolutionized how we communicate.",
    "Coding requires both creativity and logic.",
    "The human brain is an incredibly complex organ.",
    "Every day presents a new opportunity to learn something new.",
    "Consistency is key when trying to form a new habit.",
    "The sun rises in the east and sets in the west.",
    "Music can evoke powerful emotions in listeners.",
    "Space exploration has greatly expanded our understanding of the universe.",
    "Math is a universal language used across many disciplines.",
    "Environmental sustainability is critical for future generations.",
    "Innovation often begins with a simple idea.",
    "History teaches us about the mistakes and successes of the past.",
    "A positive attitude can greatly influence your day.",
    "Languages connect people across cultures and borders.",
    "Computers have become an integral part of modern life.",
    "Hard work and dedication are the foundations of success.",
    "Good communication skills are essential in almost every profession.",
    "Learning a new language opens up many opportunities.",
    "Time management is crucial for balancing work and life responsibilities.",
    "Exercise is vital for both physical and mental well-being.",
    "The ocean covers more than seventy percent of the Earth's surface.",
    "Traveling helps to broaden your horizons and experiences.",
    "A growth mindset is essential for overcoming challenges.",
    "Creative problem-solving is highly valued in the workplace.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Patience is a virtue that can help in difficult situations.",
    "The moon affects the tides on Earth.",
    "Science has given us incredible insights into how the world works.",
    "Teamwork can lead to more innovative solutions than working alone.",
    "Plants provide oxygen, which is essential for life on Earth.",
    "Writing is an excellent way to clarify your thoughts.",
    "Many great achievements were accomplished by those who never gave up.",
    "Listening is just as important as speaking in a conversation.",
    "Learning never stops, even after finishing school.",
    "The future is shaped by the decisions we make today.",
    "Reading helps improve focus, concentration, and memory.",
    "The ability to adapt is crucial in a constantly changing world.",
    "Kindness can have a ripple effect, spreading positivity to others.",
    "A good night's sleep is important for overall health.",
    "The stars we see at night are often light-years away.",
    "Mathematics is the foundation of many scientific discoveries.",
    "The internet has brought people closer together, despite the distance.",
    "Biodiversity is crucial for maintaining balanced ecosystems.",
    "Knowledge is power, but wisdom comes from experience.",
    "Perseverance can turn a difficult situation into an opportunity for growth.",
    "Learning from mistakes is one of the best ways to improve.",
    "Curiosity is the spark that drives scientific discovery.",
    "A good mentor can help guide you through challenging times.",
    "Nature has a way of balancing itself over time.",
    "The best way to predict the future is to create it.",
    "Inspiration often comes when you least expect it.",
    "Empathy is the ability to understand and share the feelings of others.",
    "Time is the most valuable resource we have."
];
