const texts = [
  // Simple Statements & Observations
  "The sun is shining brightly today.",
  "He drinks coffee every morning without fail.",
  "The old house sits on a hill overlooking the town.",
  "The train will arrive at the station in ten minutes.",
  "My favorite color has always been blue.",
  "She works as a software developer in the city.",
  "The children are playing happily in the park.",
  "This book explains the history of the world.",
  "The recipe requires three eggs and a cup of flour.",
  "Our dog barks whenever someone comes to the door.",
  "The moon is full and bright tonight.",
  "They decided to go for a long walk on the beach.",
  "The car needs to be washed soon.",
  "Winter is coming earlier this year.",
  "He forgot his keys on the kitchen table.",
  "The flowers in the garden are beautiful.",
  "Music helps me to relax after a long day.",
  "The company announced its new product last week.",
  "This is the most important part of the plan.",
  "We should try to save more money.",
  "The river flows gently towards the sea.",
  "The new restaurant has excellent reviews.",
  "She bought a new dress for the party.",
  "I have a meeting at three o'clock this afternoon.",
  "The problem is more complex than it appears.",
  "He is learning to play the guitar.",
  "The movie starts in less than an hour.",
  "The library is a quiet place to study.",
  "They live in a small apartment downtown.",
  "The bird built a nest in the tree outside my window.",

  // Questions
  "What time is it right now?",
  "Where did you put the remote control?",
  "How was your day at school?",
  "Can you help me with this heavy box?",
  "Is this the right way to the museum?",
  "Have you finished your homework yet?",
  "Why did you choose that particular color?",
  "Do you have any plans for the weekend?",
  "Could you please repeat what you just said?",
  "What kind of music do you like to listen to?",
  "How long does it take to get there by car?",
  "May I ask you a personal question?",
  "Are you coming to the party on Saturday?",
  "When is the best time to call you?",
  "Should we order pizza or cook dinner at home?",

  // Thoughts & Feelings
  "I think that's a wonderful idea.",
  "She feels much better after a good night's sleep.",
  "He was surprised by the unexpected news.",
  "They are excited about their upcoming vacation.",
  "I'm worried we might be late.",
  "We hope for a positive outcome.",
  "He regrets not studying harder for the exam.",
  "She is proud of her team's accomplishments.",
  "I feel a little tired this afternoon.",
  "They were disappointed with the final result.",
  "I believe everything will be alright in the end.",
  "He felt a sense of relief when the project was done.",
  "She is happy to help anyone in need.",
  "I wonder what the future will hold.",
  "They are confident in their ability to succeed.",

  // Common Idioms & Expressions
  "It's raining cats and dogs outside.",
  "He decided to bite the bullet and face the challenge.",
  "Let's not beat around the bush and get to the point.",
  "She passed the test with flying colors.",
  "That new phone costs an arm and a leg.",
  "He is feeling a bit under the weather today.",
  "You should take that with a grain of salt.",
  "It's time to hit the books and study.",
  "They saw eye to eye on the important issues.",
  "Good luck on your performance, break a leg!",

  // 'th' Sound Practice (/θ/ and /ð/)
  "I think their mother and father will be there.",
  "There are more than thirty-three things to do.",
  "Both of them went south together.",
  "This, that, these, and those are the other ones.",
  "Through thick and thin, they were always there.",
  "Her brother thought of another thoughtful gift.",
  "The weather there is nothing like the weather here.",

  // 'r' and 'l' Sound Practice
  "Laura and Larry really like the rural road.",
  "The truly terrible traffic was really a problem.",
  "Her long, curly, red hair is beautiful.",
  "Please bring the library books back later.",
  "All the clever girls arrived early.",
  "A really large lorry rattled along the road.",
  "Clearly, the rules are not optional.",

  // 's', 'z', 'sh', 'ch' Sound Practice
  "She sells sea shells down by the sea shore.",
  "Charles chose the cheap chairs for his shop.",
  "His strange suggestions were a surprise.",
  "The cheese shop shows its best products.",
  "My sister's reasons were not specific.",
  "These lazy animals doze in the zoo.",
  "Such choices change the future.",

  // 'v' and 'w' Sound Practice
  "We went on a very wonderful vacation.",
  "Where were the very valuable white vases?",
  "Wendy wishes we were watching the waves.",
  "We have a wide view of the whole valley.",
  "A very wise woman once gave me advice.",

  // Short vs. Long Vowels
  "Please sit in this green seat.",
  "He will leave it in the ship.",
  "Did he feel ill this whole week?",
  "Look at this good book about food.",
  "Who took the blue book you were looking at?",
  "He had to pull the boy from the deep pool.",
  "That man in the black hat has a fast car.",

  // More General Sentences
  "The earth revolves around the sun.",
  "Water is essential for all living things.",
  "The capital of France is Paris.",
  "He wrote a letter to his old friend.",
  "The internet has changed how we live.",
  "A balanced diet is key to good health.",
  "The small boat sailed across the lake.",
  "She read the entire book in one day.",
  "The old clock in the hall chimed twelve times.",
  "Every action has an equal and opposite reaction.",
  "He built a strong fence around his property.",
  "The night sky was filled with countless stars.",
  "The answer to the question was surprisingly simple.",
  "Technology continues to evolve at a rapid pace.",
  "The forest was quiet except for the sound of birds.",
  "He made a promise that he intended to keep.",
  "The store is open twenty-four hours a day.",
  "They watched the sunset from the top of the mountain.",
  "The power of a good idea should never be underestimated.",
  "Success is often the result of consistent effort.",
  "The museum has many interesting exhibits.",
  "She has a great sense of humor.",
  "The new law will take effect next month.",
  "He learned a valuable lesson from his mistake.",
  "The city looks beautiful at night.",
  "They took a different route to avoid the traffic.",
  "Honesty is a very important quality.",
  "The sound of the ocean is very calming.",
  "He decided to pursue a career in medicine.",
  "The committee will review the proposal tomorrow.",
  "She has a natural talent for painting.",
  "The evidence clearly supports his argument.",
  "The system is designed to be efficient and secure.",
  "He expressed his gratitude for all the help he received.",
  "The journey was long, but the destination was worth it.",
  "We need to find a sustainable solution to this problem.",
  "The debate covered a wide range of topics.",
  "She managed to solve the puzzle very quickly.",
  "The performance received a standing ovation.",
  "He has a deep understanding of the subject.",
  "The experiment produced some unexpected results.",
  "They are working together to achieve a common goal.",
  "The report highlights the key findings of the research.",
  "She took a moment to reflect on her decision.",
  "The organization provides support for local families.",
  "He has a positive outlook on life.",
  "The government is taking steps to improve the economy.",
  "The bridge connects the two sides of the river.",
  "She has a strong desire to make a difference in the world.",
  "The garden was filled with the sweet smell of roses.",
  "He is responsible for managing the entire department.",
  "The film tells the story of a famous historical event.",
  "They developed an innovative approach to the problem.",
  "The company is committed to customer satisfaction.",
  "He gave a compelling presentation to the board.",
  "The new building is an impressive piece of architecture.",
  "She is known for her kindness and generosity.",
  "The festival celebrates the region's cultural heritage.",
  "He is a respected member of the community.",
  "The article offers a detailed analysis of the situation.",
  "They have made significant progress in their research.",
  "The policy is designed to protect the environment.",
  "She has a remarkable ability to connect with people.",
  "The project was completed ahead of schedule and under budget.",
  "He is considered an expert in his field.",
  "The book offers practical advice for everyday problems.",
  "They are dedicated to providing high-quality service.",
  "The solution requires a creative and flexible approach.",
  "She has a passion for learning new things.",
  "The discovery had a profound impact on science.",
  "He has a clear vision for the future of the company.",
  "The community came together to support the cause.",
  "She demonstrated exceptional leadership skills.",
  "The goal is to create a more inclusive society.",
  "He played a crucial role in the success of the team.",
  "The program aims to empower young entrepreneurs.",
  "They established a foundation to help those in need.",
  "The conference brought together experts from around the world.",
  "She has a reputation for being fair and honest.",
  "The study revealed a strong correlation between the two factors.",
  "He is an advocate for social justice and equality.",
  "The organization is working to address global challenges.",
  "She has an unwavering commitment to her principles.",
  "The initiative has received widespread support.",
  "He is a pioneer in the field of renewable energy.",
];