const sentences = [
    { "sentence": "The ____ is on the table.", "answer": "book", "answerPt": "livro", "sentencePt": "O livro está sobre a mesa.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "She is holding a ____.", "answer": "pen", "answerPt": "caneta", "sentencePt": "Ela está segurando uma caneta.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "They saw a ____ in the sky.", "answer": "bird", "answerPt": "pássaro", "sentencePt": "Eles viram um pássaro no céu.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "There is a ____ in the room.", "answer": "chair", "answerPt": "cadeira", "sentencePt": "Há uma cadeira na sala.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The cat is chasing a ____.", "answer": "mouse", "answerPt": "rato", "sentencePt": "O gato está perseguindo um rato.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "Please pass me the ____.", "answer": "salt", "answerPt": "sal", "sentencePt": "Por favor, me passe o sal.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He parked the ____ in the garage.", "answer": "car", "answerPt": "carro", "sentencePt": "Ele estacionou o carro na garagem.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "I need to buy a new ____.", "answer": "phone", "answerPt": "telefone", "sentencePt": "Eu preciso comprar um novo telefone.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is shining brightly.", "answer": "sun", "answerPt": "sol", "sentencePt": "O sol está brilhando intensamente.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "She put the ____ in the fridge.", "answer": "milk", "answerPt": "leite", "sentencePt": "Ela colocou o leite na geladeira.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He is reading a ____.", "answer": "newspaper", "answerPt": "jornal", "sentencePt": "Ele está lendo um jornal.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The dog is barking at the ____.", "answer": "stranger", "answerPt": "estranho", "sentencePt": "O cachorro está latindo para o estranho.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is growing in the garden.", "answer": "flower", "answerPt": "flor", "sentencePt": "A flor está crescendo no jardim.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "I am going to the ____ tomorrow.", "answer": "beach", "answerPt": "praia", "sentencePt": "Eu vou à praia amanhã.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The children are playing with a ____.", "answer": "ball", "answerPt": "bola", "sentencePt": "As crianças estão brincando com uma bola.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He is writing a ____ to his friend.", "answer": "letter", "answerPt": "carta", "sentencePt": "Ele está escrevendo uma carta para seu amigo.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "She gave him a ____ for his birthday.", "answer": "gift", "answerPt": "presente", "sentencePt": "Ela deu a ele um presente de aniversário.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is boiling on the stove.", "answer": "water", "answerPt": "água", "sentencePt": "A água está fervendo no fogão.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ flew over the mountains.", "answer": "plane", "answerPt": "avião", "sentencePt": "O avião voou sobre as montanhas.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "They are building a new ____ downtown.", "answer": "bridge", "answerPt": "ponte", "sentencePt": "Eles estão construindo uma nova ponte no centro.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The artist painted a beautiful ____.", "answer": "portrait", "answerPt": "retrato", "sentencePt": "O artista pintou um belo retrato.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He is playing the ____ in the band.", "answer": "guitar", "answerPt": "guitarra", "sentencePt": "Ele está tocando guitarra na banda.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is very tasty.", "answer": "pizza", "answerPt": "pizza", "sentencePt": "A pizza está muito saborosa.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "She is wearing a beautiful ____.", "answer": "dress", "answerPt": "vestido", "sentencePt": "Ela está vestindo um belo vestido.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is barking loudly.", "answer": "dog", "answerPt": "cachorro", "sentencePt": "O cachorro está latindo alto.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He is watching a ____ on TV.", "answer": "movie", "answerPt": "filme", "sentencePt": "Ele está assistindo a um filme na TV.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is on the desk.", "answer": "computer", "answerPt": "computador", "sentencePt": "O computador está na mesa.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "She found a ____ in the park.", "answer": "coin", "answerPt": "moeda", "sentencePt": "Ela encontrou uma moeda no parque.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is running out of fuel.", "answer": "car", "answerPt": "carro", "sentencePt": "O carro está ficando sem combustível.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He is cooking a ____ for dinner.", "answer": "meal", "answerPt": "refeição", "sentencePt": "Ele está cozinhando uma refeição para o jantar.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The teacher gave the students a ____.", "answer": "test", "answerPt": "teste", "sentencePt": "O professor deu aos alunos um teste.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "They are planning a trip to the ____.", "answer": "mountains", "answerPt": "montanhas", "sentencePt": "Eles estão planejando uma viagem para as montanhas.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He is reading a ____ under the tree.", "answer": "book", "answerPt": "livro", "sentencePt": "Ele está lendo um livro debaixo da árvore.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The baby is playing with a ____.", "answer": "toy", "answerPt": "brinquedo", "sentencePt": "O bebê está brincando com um brinquedo.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "She took a ____ of water from the fridge.", "answer": "bottle", "answerPt": "garrafa", "sentencePt": "Ela pegou uma garrafa de água na geladeira.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "He bought a ____ at the store.", "answer": "shirt", "answerPt": "camisa", "sentencePt": "Ele comprou uma camisa na loja.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "They are having a ____ in the park.", "answer": "picnic", "answerPt": "piquenique", "sentencePt": "Eles estão fazendo um piquenique no parque.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "The ____ is flying over the city.", "answer": "drone", "answerPt": "drone", "sentencePt": "O drone está voando sobre a cidade.", "views": 0, "errors": 0, "correct": 0 },
    { "sentence": "She painted the walls with a new ____.", "answer": "color", "answerPt": "cor", "sentencePt": "Ela pintou as paredes com uma nova cor.", "views": 0, "errors": 0, "correct": 0 },
];
