const sentences = [
  {
    sentence: "The ____ is on the table.",
    answer: "book",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She is holding a ____.",
    answer: "pen",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "They saw a ____ in the sky.",
    answer: "bird",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "There is a ____ in the room.",
    answer: "chair",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The cat is chasing a ____.",
    answer: "mouse",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "Please pass me the ____.",
    answer: "salt",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He parked the ____ in the garage.",
    answer: "car",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "I need to buy a new ____.",
    answer: "phone",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is shining brightly.",
    answer: "sun",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She put the ____ in the fridge.",
    answer: "milk",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is reading a ____.",
    answer: "newspaper",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The dog is barking at the ____.",
    answer: "stranger",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is growing in the garden.",
    answer: "flower",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "I am going to the ____ tomorrow.",
    answer: "beach",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The children are playing with a ____.",
    answer: "ball",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is writing a ____ to his friend.",
    answer: "letter",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She gave him a ____ for his birthday.",
    answer: "gift",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is boiling on the stove.",
    answer: "water",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ flew over the mountains.",
    answer: "plane",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "They are building a new ____ downtown.",
    answer: "bridge",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The artist painted a beautiful ____.",
    answer: "portrait",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is playing the ____ in the band.",
    answer: "guitar",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is very tasty.",
    answer: "pizza",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She is wearing a beautiful ____.",
    answer: "dress",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is barking loudly.",
    answer: "dog",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is watching a ____ on TV.",
    answer: "movie",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is on the desk.",
    answer: "computer",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She found a ____ in the park.",
    answer: "coin",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is running out of fuel.",
    answer: "car",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is cooking a ____ for dinner.",
    answer: "meal",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The teacher gave the students a ____.",
    answer: "test",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "They are planning a trip to the ____.",
    answer: "mountains",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is reading a ____ under the tree.",
    answer: "book",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The baby is playing with a ____.",
    answer: "toy",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She took a ____ of water from the fridge.",
    answer: "bottle",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He bought a ____ at the store.",
    answer: "shirt",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "They are having a ____ in the park.",
    answer: "picnic",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is flying over the city.",
    answer: "drone",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She painted the walls with a new ____.",
    answer: "color",
    views: 0,
    errors: 0,
    correct: 0,
  },
  // Added sentences start here
  {
    sentence: "Please close the ____ when you leave.",
    answer: "door",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "A spider has eight ____.",
    answer: "legs",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The moon orbits the ____.",
    answer: "earth",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "I would like a cup of ____.",
    answer: "coffee",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is riding his ____ to work.",
    answer: "bicycle",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The doctor gave me a ____.",
    answer: "prescription",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "You use your ____ to see.",
    answer: "eyes",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ arrived at the station on time.",
    answer: "train",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The leaves turn ____ in the autumn.",
    answer: "brown",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "Knowledge is ____.",
    answer: "power",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "I need to charge my ____.",
    answer: "laptop",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "Bees produce ____.",
    answer: "honey",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She sent an ____ to her manager.",
    answer: "email",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The heart pumps ____ through the body.",
    answer: "blood",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is learning to play the ____.",
    answer: "piano",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The city is famous for its tall ____.",
    answer: "buildings",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She baked a delicious ____ for dessert.",
    answer: "cake",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is the king of the jungle.",
    answer: "lion",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "It's cold outside, wear a warm ____.",
    answer: "jacket",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He works in a busy ____.",
    answer: "office",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is ringing, can you answer it?",
    answer: "phone",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "We need to cross the ____ to get to the other side.",
    answer: "river",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The baby is sleeping in the ____.",
    answer: "crib",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The students are listening to the ____.",
    answer: "teacher",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "I need a ____ and fork to eat my salad.",
    answer: "knife",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is full of stars tonight.",
    answer: "sky",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is writing with a ____.",
    answer: "pencil",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is green.",
    answer: "grass",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She is wearing a new pair of ____.",
    answer: "shoes",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He is drinking a glass of ____.",
    answer: "juice",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is shining through the window.",
    answer: "light",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "They are sitting on a ____ in the park.",
    answer: "bench",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "I need to finish my ____ before I can play.",
    answer: "homework",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ship sailed across the ____.",
    answer: "ocean",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The fireman climbed the ____.",
    answer: "ladder",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She is listening to ____ on her headphones.",
    answer: "music",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ on the wall shows the correct time.",
    answer: "clock",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The farmer is driving a ____.",
    answer: "tractor",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "I need to buy groceries from the ____.",
    answer: "store",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He hit the ____ with the bat.",
    answer: "ball",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ of the book is very interesting.",
    answer: "story",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She is wearing a ____ to protect her from the sun.",
    answer: "hat",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is used for cutting paper.",
    answer: "scissors",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He fixed the leak with a ____.",
    answer: "wrench",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The police officer directs ____.",
    answer: "traffic",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ swims in the water.",
    answer: "fish",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She is watering the ____ in her garden.",
    answer: "plants",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "He packed his clothes in a ____.",
    answer: "suitcase",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "The ____ is my favorite fruit.",
    answer: "apple",
    views: 0,
    errors: 0,
    correct: 0,
  },
  {
    sentence: "She keeps her money in a ____.",
    answer: "wallet",
    views: 0,
    errors: 0,
    correct: 0,
  },
];